using System.Reflection;
using System.Text;

namespace J18n.SourceGenerators;

public static class SourceEmitter
{
    private readonly static string Version =
        Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "1.0.0.0";
    
    public static string Emit(ResourceItem item)
    {
        var source = new StringBuilder();
        
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine();
        source.AppendLine($"namespace {item.Namespace}");
        source.AppendLine("{");
        source.AppendLine($"    [System.CodeDom.Compiler.GeneratedCode(\"LocalizationMarkerGenerator\", \"{Version}\")]");
        source.AppendLine("    [System.Diagnostics.DebuggerNonUserCode]");
        source.AppendLine($"    public sealed partial class {item.ClassName}");
        source.AppendLine("    {");
        source.AppendLine("    }");
        source.AppendLine("}");
        
        return source.ToString();
    }
}